### ISSUE TITLE
Mean Errors!

### ISSUE THREAD

**Issue by puffyboa** [katzrkool/Quizlet-Match-Player#1]
It looks like I need [subprocess](https://docs.python.org/3/library/subprocess.html), which you forgot to mention in the README! SHAME

It also needs me to have the correct webdrivers ([install chromedriver](https://chromedriver.storage.googleapis.com/index.html?path=2.32/)). These need to be in their default locations, and put in PATH, which would also be good to include in the README.

```Traceback (most recent call last):
  File "C:\Users\julia\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\common\service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "C:\Users\julia\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Users\julia\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/julia/Documents/GitHub/Quizlet-Match-Player/quizlet.py", line 11, in <module>
    driver=webdriver.Chrome()
  File "C:\Users\julia\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 62, in __init__
    self.service.start()
  File "C:\Users\julia\AppData\Local\Programs\Python\Python35-32\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home```

**Comment by katzrkool** [comment]
Looking into it

**Comment by katzrkool** [comment]
As far as I can tell, subprocess is already installed with Python. Maybe your python is outdated?

And I'll fix the drivers, I installed them for another project and forgot that they had to be installed separately

**Comment by puffyboa** [comment]
It looks like I misinterpreted the error - it's not actually a missing module error. According to this [StackOverflow post](https://stackoverflow.com/questions/26144305/how-to-install-subprocess-module-for-python):

> The error that you show in your question update is nothing more prosaic than a file not found error. Likely the executable file that you are attempting to call Popen on cannot be found.

> That traceback indicates that subprocess is installed and has been imported. The problem is simply that the call to subprocess.call('py.test') is failing.

[I looked it up](https://stackoverflow.com/questions/41788251/selenium-webdriver-for-python-traceback-errors) and I think that the two errors are actually because of the same thing - I don't have the webdriver set up.

**Comment by katzrkool** [comment]
K, sounds good. I updated the readme to include driver links. Will be launching new release in a couple minutes
